/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.List;
import java.util.Scanner;

public class App {
    
    /* OBJ10-J Do not use public static nonfinal fields
    to deterimine if the user has admin level access in case of feauture 
    admin level features the access level is detemrined here and is unchangable during runtime
    */
    public static final class premissions {
        public static final String USER_ACCESS = "USER";
    }


     static User SignOn(){
        Scanner scanner = new Scanner(System.in);
       
        System.out.println("Enter your username:");
        String username = scanner.nextLine(); // Read username input

        System.out.println("Enter your Password:");
        String password = scanner.nextLine(); // Read password input
        User userProfile = verifyLogon(username, password);
        if(userProfile != null){ // Placeholder for actual authentication logic
            System.out.println("Sign on successful! Welcome to the Notes App!");

            return userProfile;
        } else {
            System.out.println("Sign on failed! Please check your credentials and try again.");
            return null;
        }
        
    }

    static User verifyLogon(String username, String password){
        // placeholder for testing
       User user = new User(username, password);
        return user;
        // Placeholder for actual authentication logic you can dowhatever wtih this guys
        // User theUser;
        // if(true){ // Replace with actual condition to verify username and password
        //     return theUser; // Return a the logged on User object if authentication is successful
        // } else {
        //     return null; // Return null if authentication fails
        // }
    }

    static void createAccount(){
        Scanner scanner = new Scanner(System.in);
        System.out.println("Creating a new account...");
        System.out.println("Enter a username:");
        String username = scanner.nextLine();
        System.out.println("Enter a password:");
        String password = scanner.nextLine();
        User user = new User(username, password); // need to implement the saving to the db
        System.out.println("Account created successfully!");
    }

    static void runtime(User user){
        System.out.println("Welcome " + user.getUsername() + "! You can now create and manage your notes.");
        List<Note> userNotes = user.getNotes();
        System.out.println("Here are your current notes:");
        if(userNotes.isEmpty()){
            System.out.println("You have no notes yet. Start by creating a new note!");
        } else {
        for(Note note : userNotes){
            
            System.out.println("Note Title: " + note.getTitle());
        }
    }
        Scanner scanner = new Scanner(System.in);
        System.out.println("What would you like to do? (Type 'create', 'view', 'edit', or 'delete')");
        String action = scanner.nextLine();

        if(action.equalsIgnoreCase("create")){
            System.out.println("Enter the title of your new note:");
            String title = scanner.nextLine();
            for(Note note : userNotes){
                if(note.getTitle().equalsIgnoreCase(title)){
                    System.out.println("A note with this title already exists! Please choose a different title.");
                    return; // Exit the method to prevent creating a note with a duplicate title
                }
            }
            System.out.println("Enter the content of your new note:");
            String content = scanner.nextLine();
            Note newNote = new Note(user.getId(), title, content);
            user.addNote(newNote);
            System.out.println("Note created successfully!");

        } else if(action.equalsIgnoreCase("view")){

            /* OBJ09-J we compare if the class being checked is 
            is the same as the user class and nothing else for security reasons
             */
                if (user.getClass() != User.class) {
                    System.out.println("Error: Invalid user object type.");
                    return;
                }
            System.out.println("Enter the title of the note you want to view:");
            String noteTitle = scanner.nextLine();
            Note noteToView = null; 
            for(Note note : userNotes){
                if(note.getTitle().equalsIgnoreCase(noteTitle)){
                    noteToView = note;
                    break;
                }
            }
            if(noteToView != null){
                System.out.println("Note Title: " + noteToView.getTitle());
                System.out.println("Note Content: " + noteToView.getContent());
            } else {
                System.out.println("Note not found! Please check the title and try again.");
            }

        } else if(action.equalsIgnoreCase("edit")){
            System.out.println("Enter the title of the note you want to edit:");
            String noteTitle = scanner.nextLine();
            Note noteToEdit = null; 
            for(Note note : userNotes){
                if(note.getTitle().equalsIgnoreCase(noteTitle)){
                    noteToEdit = note;
                    break;
                }
            }
            if(noteToEdit != null){
                //does NOT append to the existing content, it replaces it entirely let me know if you want it to append instead
                System.out.println("Enter the new content for your note:");
                String newContent = scanner.nextLine();
                noteToEdit.setContent(newContent);
                System.out.println("Note edited successfully!"); 
            } else {
                System.out.println("Note not found! Please check the title and try again.");
            }

        } else if(action.toLowerCase().startsWith("delete")){
            System.out.println("Enter the title of the note you want to delete:");
            String noteTitle = scanner.nextLine();
            Note noteToDelete = null; 
            for(Note note : userNotes){
                if(note.getTitle().equalsIgnoreCase(noteTitle)){
                    noteToDelete = note;
                    break;
                }
            }
            if(noteToDelete != null){
                user.removeNote(noteToDelete.getTitle());
                System.out.println("Note deleted successfully!");
            } else {
                System.out.println("Note not found! Please check the title and try again.");
            }

        } else {
            System.out.println("Invalid action! Please restart the application and choose a valid action.");
        }
        
    }
    public static void main(String[] args) {
     System.out.println("Hello Welcome to the Notes App! This sign on is a " + premissions.USER_ACCESS + " access level");
      System.out.println("Would you like to sign on or create an account? (Type 'SignOn' or 'create')");
      Scanner scanner = new Scanner(System.in);
        String choice = scanner.nextLine();
    if(choice.equalsIgnoreCase("SignOn")){
        User signedOnUser = SignOn();
        if(signedOnUser != null){
            System.out.println("You are now signed on to the Notes App!");
            runtime(signedOnUser);
        } else {
            System.out.println("Sign on failed. Please try again.");
            SignOn(); // Recursively call SignOn() to attempt sign-on again
        }
    } else if(choice.equalsIgnoreCase("create")){
       createAccount(); // Placeholder for account creation logic .
    }else{
        System.out.println("Invalid choice! Please restart the application and choose either 'SignOn' or 'create'.");
    }
    scanner.close();

    }
}
