/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.text.Normalizer;
import java.util.List;
import java.util.Scanner;
import java.util.regex.Pattern;

import org.example.persistence.UserSaver;
import org.example.persistence.UserSaver.UserException;

public class App {
    
    /* OBJ10-J Do not use public static nonfinal fields
    to deterimine if the user has admin level access in case of feauture 
    admin level features the access level is detemrined here and is unchangable during runtime
    */
    public static final class premissions {
        public static final String USER_ACCESS = "USER";
    }

    /* FIO14-J: Perform proper cleanup at program termination
    A shared Scanner reference is maintained so that it can be properly
    closed during shutdown, whether the program exits normally or is
    abruptly terminated (e.g. Ctrl+C).
    */
    private static Scanner appScanner = null;

    /* IDS00-J: Prevent SQL injection vulnerabilities
    SQL injection patterns used to detect and reject malicious input
    before it reaches the database layer
    */
    private static final Pattern[] SQL_INJECTION_PATTERNS = {
        Pattern.compile("('|(\\-\\-)|(;)|(\\|))", Pattern.CASE_INSENSITIVE),
        Pattern.compile("\\b(union|select|insert|update|delete|drop|create|alter|exec|execute)\\b", Pattern.CASE_INSENSITIVE),
        Pattern.compile("(\\bor\\b|\\band\\b)\\s*[=<>]", Pattern.CASE_INSENSITIVE)
    };

    /**
     * IDS00-J: Checks whether the supplied input contains common SQL injection patterns.
     *
     * @param userInput The raw input to evaluate
     * @return {@code true} if no injection patterns are detected; {@code false} otherwise
     * @throws IllegalArgumentException if {@code userInput} is {@code null}
     */
    static boolean isSqlSafe(String userInput) {
        if (userInput == null) {
            throw new IllegalArgumentException("Input cannot be null");
        }
        // Check against SQL injection patterns
        for (Pattern pattern : SQL_INJECTION_PATTERNS) {
            if (pattern.matcher(userInput).find()) {
                return false; // SQL injection pattern detected
            }
        }
        return true; // Input appears safe from SQL injection
    }

    /**
     * IDS00-J: Removes characters and keywords commonly used in SQL injection attempts.
     *
     * @param userInput The raw input to clean
     * @return A sanitized version of the input with risky tokens removed
     * @throws IllegalArgumentException if {@code userInput} is {@code null}
     */
    static String sanitizeSqlInput(String userInput) {
        if (userInput == null) {
            throw new IllegalArgumentException("Input cannot be null");
        }
        // Remove SQL injection characters
        String cleaned = userInput.replaceAll("[';\"\\-\\-]", "");
        // Remove SQL keywords (case insensitive)
        cleaned = cleaned.replaceAll("(?i)\\b(union|select|insert|update|delete|drop|create|alter|exec|execute)\\b", "");
        // Remove dangerous operators used in SQL injection
        cleaned = cleaned.replaceAll("(?i)(\\bor\\b|\\band\\b)\\s*[=<>]", "");
        return cleaned.trim();
    }

    /**
     * IDS00-J: Validates input for SQL injection patterns and sanitizes it if safe.
     *
     * @param userInput The input to process
     * @return Sanitized input if safe, {@code null} if empty or malicious
     */
    static String processSqlInput(String userInput) {
        if (userInput == null || userInput.trim().isEmpty()) {
            return null;
        }
        // First check if input is safe
        if (!isSqlSafe(userInput)) {
            System.err.println("SQL injection attempt detected: " + userInput);
            return null; // Reject potentially malicious input
        }
        // Sanitize for extra protection
        String sanitized = sanitizeSqlInput(userInput);
        System.out.println("Original: " + userInput);
        System.out.println("Processed: " + sanitized);
        return sanitized;
    }

    /**
     * IDS01-J: Normalizes user input before validation.
     * Normalization must happen BEFORE validation to prevent bypass attacks using
     * alternate Unicode representations.
     *
     * @param rawInput The untrusted raw input to normalize
     * @return The normalized input
     */
    static String normalizeInput(String rawInput) {
        if (rawInput == null || rawInput.isEmpty()) {
            return null;
        }
        
        String normalized = Normalizer.normalize(rawInput, Normalizer.Form.NFKC);
        return normalized;
    }

    /**
     * IDS11-J: Performs string modifications BEFORE validation.
     * This method cleans the input by trimming whitespace and removing control characters,
     * then validates the cleaned result. All modifications happen before validation
     * to prevent bypass attacks.
     *
     * @param rawInput The untrusted raw input to clean and validate
     * @return The cleaned input if valid, or null if invalid
     * @throws IllegalArgumentException if the cleaned input fails validation
     */
    static String cleanAndValidateInput(String rawInput) {
        if (rawInput == null) {
            throw new IllegalArgumentException("Input cannot be null");
        }

        /* IDS11-J: Perform ALL string modifications BEFORE validation */
        String cleaned = rawInput.trim();
        
        /* Remove control characters and other unsafe Unicode categories */
        cleaned = cleaned.replaceAll("[\\p{Cc}\\p{Cn}]", "");
        
        /* IDS11-J: NOW validate the cleaned string */
        if (cleaned.length() < 3 || cleaned.length() > 50) {
            throw new IllegalArgumentException("Input must be 3-50 characters long after cleaning");
        }
        
        /* Validate that it only contains safe characters after cleaning */
        if (!Pattern.matches("^[a-zA-Z0-9_@.\\s-]+$", cleaned)) {
            throw new IllegalArgumentException("Input contains invalid characters after cleaning");
        }
        
        return cleaned;
    }


     static User SignOn(){
        Scanner scanner = new Scanner(System.in);
       
        System.out.println("Enter your username:");
        String username = scanner.nextLine(); // Read username input

        /* IDS00-J: Validate and sanitize username input to prevent SQL injection */
        username = processSqlInput(username);
        if (username == null) {
            System.out.println("Invalid username input detected. Please try again.");
            return null;
        }

        System.out.println("Enter your Password:");
        String password = scanner.nextLine(); // Read password input
        User userProfile = verifyLogon(username, password);
        if(userProfile != null){ // Placeholder for actual authentication logic
            System.out.println("Sign on successful! Welcome to the Notes App!");

            return userProfile;
        } else {
            System.out.println("Sign on failed! Please check your credentials and try again.");
            return null;
        }
        
    }

    static User verifyLogon(String username, String password){
        /* ERR08-J: Do not allow NullPointerExceptions - check for null explicitly
        and provide clear error messages to the caller */
        if (username == null || username.isEmpty()) {
            System.err.println("Username cannot be null or empty");
            return null;
        }
        if (password == null || password.isEmpty()) {
            System.err.println("Password cannot be null or empty");
            return null;
        }
        
        // Perform login attempt with valid credentials
        try {
            return UserSaver.loadUser(username, password);
        } catch (UserException | SecurityException e) {
            e.printStackTrace();
        }

        return null;
    }

    static void createAccount(){
        Scanner scanner = new Scanner(System.in);
        System.out.println("Creating a new account...");
        System.out.println("Enter a username:");
        String username = scanner.nextLine();

        /* IDS00-J: Validate and sanitize username input to prevent SQL injection */
        username = processSqlInput(username);
        if (username == null) {
            System.out.println("Invalid username input detected. Account creation aborted.");
            return;
        }

        System.out.println("Enter a password:");
        String password = scanner.nextLine();

        User user = new User(username, password); // need to implement the saving to the db

        try {
            UserSaver.saveUser(user);
            System.out.println("Account created successfully!");
        } catch (UserException e) {
            e.printStackTrace();
        }
    }

    static void runtime(User user){
        System.out.println("Welcome " + user.getUsername() + "! You can now create and manage your notes.");
        List<Note> userNotes = user.getNotes();
        System.out.println("Here are your current notes:");
        if(userNotes.isEmpty()){
            System.out.println("You have no notes yet. Start by creating a new note!");
        } else {
        for(Note note : userNotes){
            
            System.out.println("Note Title: " + note.getTitle());
        }
    }
        Scanner scanner = new Scanner(System.in);
        System.out.println("What would you like to do? (Type 'create', 'view', 'edit', 'delete', 'export', 'import', 'search', 'history', or 'clear history')");
        String action = scanner.nextLine();

        if(action.equalsIgnoreCase("create")){
            System.out.println("Enter the title of your new note:");
            String title = scanner.nextLine();
            for(Note note : userNotes){
                if(note.getTitle().equalsIgnoreCase(title)){
                    System.out.println("A note with this title already exists! Please choose a different title.");
                    return; // Exit the method to prevent creating a note with a duplicate title
                }
            }
            System.out.println("Enter the content of your new note:");
            String content = scanner.nextLine();
            Note newNote = new Note(title, content);
            user.addNote(newNote);
            
            try {
                UserSaver.saveUser(user);
                System.out.println("Note created successfully!");
            } catch (UserException e) {
                e.printStackTrace();
            }
        } else if(action.equalsIgnoreCase("view")){

            /* OBJ09-J we compare if the class being checked is 
            is the same as the user class and nothing else for security reasons
             */
                if (user.getClass() != User.class) {
                    System.out.println("Error: Invalid user object type.");
                    return;
                }
            System.out.println("Enter the title of the note you want to view:");
            String noteTitle = scanner.nextLine();
            Note noteToView = null; 
            for(Note note : userNotes){
                if(note.getTitle().equalsIgnoreCase(noteTitle)){
                    noteToView = note;
                    break;
                }
            }
            if(noteToView != null){
                System.out.println("Note Title: " + noteToView.getTitle());
                System.out.println("Note Content: " + noteToView.getContent());
            } else {
                System.out.println("Note not found! Please check the title and try again.");
            }

        } else if(action.equalsIgnoreCase("edit")){
            System.out.println("Enter the title of the note you want to edit:");
            String noteTitle = scanner.nextLine();
            Note noteToEdit = null; 
            for(Note note : userNotes){
                if(note.getTitle().equalsIgnoreCase(noteTitle)){
                    noteToEdit = note;
                    break;
                }
            }
            if(noteToEdit != null){
                //does NOT append to the existing content, it replaces it entirely let me know if you want it to append instead
                System.out.println("Enter the new content for your note:");
                String newContent = scanner.nextLine();
                noteToEdit.setContent(newContent);

                try {
                    UserSaver.saveUser(user);
                    System.out.println("Note edited successfully!"); 
                } catch (UserException e) {
                    e.printStackTrace();
                }
            } else {
                System.out.println("Note not found! Please check the title and try again.");
            }

        } else if(action.equalsIgnoreCase("export")){
            System.out.println("Enter the directory to export notes to (press Enter for default 'data/exports'):");
            String exportDir = scanner.nextLine().trim();
            if (exportDir.isEmpty()) {
                exportDir = "data/exports";
            }
            System.out.println("Exporting all notes in parallel to " + exportDir + "...");
            user.exportAllNotesParallel(exportDir);

        } else if(action.equalsIgnoreCase("import")){
            System.out.println("Enter the directory to import notes from (press Enter for default 'data/exports'):");
            String importDir = scanner.nextLine().trim();
            if (importDir.isEmpty()) {
                importDir = "data/exports";
            }
            System.out.println("Importing notes from " + importDir + "...");
            user.importNotesParallel(importDir);
            try {
                UserSaver.saveUser(user);
                System.out.println("Imported notes saved successfully!");
            } catch (UserException e) {
                e.printStackTrace();
            }

        } else if(action.equalsIgnoreCase("search")){
            System.out.println("Enter a keyword to search your notes:");
            String keyword = scanner.nextLine();
            List<Note> results = NoteSearcher.search(userNotes, keyword);
            if (results.isEmpty()) {
                System.out.println("No notes matched '" + keyword + "'.");
            } else {
                System.out.println("Found " + results.size() + " matching note(s):");
                for (Note note : results) {
                    System.out.println("  - " + note.getTitle());
                }
            }

        } else if(action.equalsIgnoreCase("history")){
            List<String> history = NoteSearcher.getSearchHistory();
            if (history.isEmpty()) {
                System.out.println("No search history.");
            } else {
                System.out.println("Search history:");
                for (int i = 0; i < history.size(); i++) {
                    System.out.println("  " + (i + 1) + ". " + history.get(i));
                }
            }

        } else if(action.equalsIgnoreCase("clear history")){
            NoteSearcher.clearHistory();
            System.out.println("Search history cleared.");

        } else if(action.toLowerCase().startsWith("delete")){
            System.out.println("Enter the title of the note you want to delete:");
            String noteTitle = scanner.nextLine();
            Note noteToDelete = null; 
            for(Note note : userNotes){
                if(note.getTitle().equalsIgnoreCase(noteTitle)){
                    noteToDelete = note;
                    break;
                }
            }
            if(noteToDelete != null){
                user.removeNote(noteToDelete.getTitle());

                try {
                    UserSaver.saveUser(user);
                    System.out.println("Note deleted successfully!");
                } catch (UserException e) {
                    e.printStackTrace();
                }
            } else {
                System.out.println("Note not found! Please check the title and try again.");
            }

        } else {
            System.out.println("Invalid action! Please restart the application and choose a valid action.");
        }
        
    }

    /**
     * FIO14-J: Manually closes all open resources before program termination.
     * This ensures resources such as the Scanner are properly released.
     */
    static void manualCleanup() {
        if (appScanner != null) {
            System.out.println("Manual cleanup: Closing scanner");
            appScanner.close();
            appScanner = null;
        }
    }

    /**
     * FIO14-J: Performs proper cleanup and then terminates the program.
     * Uses Runtime.exit() instead of Runtime.halt() so that shutdown hooks
     * are allowed to run.
     *
     * @param exitCode Exit code for the program (0 = normal, nonzero = error)
     */
    static void safeExit(int exitCode) {
        try {
            // Perform manual cleanup first
            manualCleanup();

            // Use exit() instead of halt() to allow shutdown hooks to run
            System.out.println("Exiting safely...");
            Runtime.getRuntime().exit(exitCode);
        } catch (Exception e) {
            System.err.println("Error during cleanup: " + e.getMessage());
            // Force exit if cleanup fails
            Runtime.getRuntime().halt(1);
        }
    }

    public static void main(String[] args) {
     System.out.println("Hello Welcome to the Notes App! This sign on is a " + premissions.USER_ACCESS + " access level");

      /* FIO14-J: Register a shutdown hook to ensure the Scanner is closed
      even if the program is abruptly terminated (e.g. Ctrl+C or kill signal).
      Uses Runtime.exit() path so hooks are invoked; never Runtime.halt().
      */
      appScanner = new Scanner(System.in);
      Runtime.getRuntime().addShutdownHook(new Thread(() -> {
          if (appScanner != null) {
              System.out.println("Shutdown hook: Closing scanner");
              appScanner.close();
              appScanner = null;
          }
      }));

      System.out.println("Would you like to sign on or create an account? (Type 'SignOn' or 'create')");
        String choice = appScanner.nextLine();
    if(choice.equalsIgnoreCase("SignOn")){
        User signedOnUser = SignOn();
        if(signedOnUser != null){
            System.out.println("You are now signed on to the Notes App!");
            runtime(signedOnUser);
        } else {
            System.out.println("Sign on failed. Please try again.");
            SignOn(); // Recursively call SignOn() to attempt sign-on again
        }
    } else if(choice.equalsIgnoreCase("create")){
       createAccount(); // Placeholder for account creation logic .
    }else{
        System.out.println("Invalid choice! Please restart the application and choose either 'SignOn' or 'create'.");
    }

    /* FIO14-J: Perform manual cleanup and exit safely */
    safeExit(0);

    }
}
